apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: minio-ss-issuer
  namespace: minio-operator
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
spec:
  selfSigned: {}
