apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator

commonAnnotations:
  operator.min.io/authors: "MinIO, Inc."
  operator.min.io/license: "AGPLv3"
  operator.min.io/support: "https://subnet.min.io"
  operator.min.io/version: v7.1.1

commonLabels:
  app.kubernetes.io/name: operator

resources:
  - base/namespace.yaml
  - base/service-account.yaml
  - base/cluster-role.yaml
  - base/cluster-role-binding.yaml
  - base/crds/
  - base/service.yaml
  - base/deployment.yaml
  - base/certificate-operator.yaml
  - base/operator-ca-issuer.yaml
  - base/sts-tls-certificate.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minio-operator
      namespace: minio-operator
    spec:
      template:
        spec:
          containers:
            - name: minio-operator
              env:
                - name: OPERATOR_STS_AUTO_TLS_ENABLED
                  value: "off"
                - name: OPERATOR_STS_ENABLED
                  value: "on"
