apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-operator-ss-cert
  namespace: minio-tenant
spec:
  isCA: true
  commonName: minio-operator.corp.internal
  secretName: minio-operator-ss-cert
  duration: 8760h
  renewBefore: 240h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfgined-root
    kind: ClusterIssuer
    group: cert-manager.io

